services:

  app:
    build:
      context: .
    container_name: ${APP_NAME}
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${SWAGGER_PORT}:${SWAGGER_PORT}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started

  db:
    image: postgres:16.3-alpine3.20
    container_name: ${APP_NAME}_${DB_HOST}
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    container_name: ${MIGRATOR_NAME}
    restart: on-failure

  redis:
    image: redis:7.4.0-alpine3.20
    container_name: ${APP_NAME}_redis
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    volumes:
      - redisdata:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - ${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}
    env_file:
      - .env

  kafka1:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS_1}

  kafka2:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka2
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS_2}

  kafka3:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka3
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS_3}

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8082:8080"
    env_file:
      - .env

volumes:
  pgdata:
  redisdata:
