services:

  server:
    image: ${DOCKER_USERNAME}/${DOCKER_SERVER_IMAGE}:latest
    container_name: server
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    env_file:
      - .env

  db:
    image: postgres:16.3-alpine3.20
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  migrator:
    image: ${DOCKER_USERNAME}/${DOCKER_MIGRATOR_IMAGE}:latest
    container_name: migrator
    restart: on-failure

volumes:
  pgdata: