services:

  server:
    build:
      context: .
    container_name: server
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    networks:
      - auth_network
    env_file:
      - .env

  db:
    image: postgres:14-alpine3.17
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    networks:
      - auth_network
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    container_name: migrator
    networks:
      - auth_network
    restart: on-failure

networks:
  auth_network:
    driver: bridge

volumes:
  pgdata: