// Code generated by http://github.com/gojuno/minimock (v3.3.14). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/mikhailsoldatkin/auth/internal/repository.UserRepository -o user_repository_minimock.go -n UserRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/mikhailsoldatkin/auth/internal/repository/user/pg/filter"
	"github.com/mikhailsoldatkin/auth/internal/service/user/model"
)

// UserRepositoryMock implements repository.UserRepository
type UserRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCheckUsersExist          func(ctx context.Context, ids []int64) (err error)
	inspectFuncCheckUsersExist   func(ctx context.Context, ids []int64)
	afterCheckUsersExistCounter  uint64
	beforeCheckUsersExistCounter uint64
	CheckUsersExistMock          mUserRepositoryMockCheckUsersExist

	funcCreate          func(ctx context.Context, user *model.User) (i1 int64, err error)
	inspectFuncCreate   func(ctx context.Context, user *model.User)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mUserRepositoryMockCreate

	funcDelete          func(ctx context.Context, id int64) (err error)
	inspectFuncDelete   func(ctx context.Context, id int64)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mUserRepositoryMockDelete

	funcGet          func(ctx context.Context, filter filter.UserFilter) (up1 *model.User, err error)
	inspectFuncGet   func(ctx context.Context, filter filter.UserFilter)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mUserRepositoryMockGet

	funcGetEndpointRoles          func(ctx context.Context, endpoint string) (sa1 []string, err error)
	inspectFuncGetEndpointRoles   func(ctx context.Context, endpoint string)
	afterGetEndpointRolesCounter  uint64
	beforeGetEndpointRolesCounter uint64
	GetEndpointRolesMock          mUserRepositoryMockGetEndpointRoles

	funcList          func(ctx context.Context, limit int64, offset int64) (upa1 []*model.User, err error)
	inspectFuncList   func(ctx context.Context, limit int64, offset int64)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mUserRepositoryMockList

	funcUpdate          func(ctx context.Context, updates *model.User) (err error)
	inspectFuncUpdate   func(ctx context.Context, updates *model.User)
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mUserRepositoryMockUpdate
}

// NewUserRepositoryMock returns a mock for repository.UserRepository
func NewUserRepositoryMock(t minimock.Tester) *UserRepositoryMock {
	m := &UserRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CheckUsersExistMock = mUserRepositoryMockCheckUsersExist{mock: m}
	m.CheckUsersExistMock.callArgs = []*UserRepositoryMockCheckUsersExistParams{}

	m.CreateMock = mUserRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*UserRepositoryMockCreateParams{}

	m.DeleteMock = mUserRepositoryMockDelete{mock: m}
	m.DeleteMock.callArgs = []*UserRepositoryMockDeleteParams{}

	m.GetMock = mUserRepositoryMockGet{mock: m}
	m.GetMock.callArgs = []*UserRepositoryMockGetParams{}

	m.GetEndpointRolesMock = mUserRepositoryMockGetEndpointRoles{mock: m}
	m.GetEndpointRolesMock.callArgs = []*UserRepositoryMockGetEndpointRolesParams{}

	m.ListMock = mUserRepositoryMockList{mock: m}
	m.ListMock.callArgs = []*UserRepositoryMockListParams{}

	m.UpdateMock = mUserRepositoryMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*UserRepositoryMockUpdateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserRepositoryMockCheckUsersExist struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockCheckUsersExistExpectation
	expectations       []*UserRepositoryMockCheckUsersExistExpectation

	callArgs []*UserRepositoryMockCheckUsersExistParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockCheckUsersExistExpectation specifies expectation struct of the UserRepository.CheckUsersExist
type UserRepositoryMockCheckUsersExistExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockCheckUsersExistParams
	paramPtrs *UserRepositoryMockCheckUsersExistParamPtrs
	results   *UserRepositoryMockCheckUsersExistResults
	Counter   uint64
}

// UserRepositoryMockCheckUsersExistParams contains parameters of the UserRepository.CheckUsersExist
type UserRepositoryMockCheckUsersExistParams struct {
	ctx context.Context
	ids []int64
}

// UserRepositoryMockCheckUsersExistParamPtrs contains pointers to parameters of the UserRepository.CheckUsersExist
type UserRepositoryMockCheckUsersExistParamPtrs struct {
	ctx *context.Context
	ids *[]int64
}

// UserRepositoryMockCheckUsersExistResults contains results of the UserRepository.CheckUsersExist
type UserRepositoryMockCheckUsersExistResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Optional() *mUserRepositoryMockCheckUsersExist {
	mmCheckUsersExist.optional = true
	return mmCheckUsersExist
}

// Expect sets up expected params for UserRepository.CheckUsersExist
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Expect(ctx context.Context, ids []int64) *mUserRepositoryMockCheckUsersExist {
	if mmCheckUsersExist.mock.funcCheckUsersExist != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Set")
	}

	if mmCheckUsersExist.defaultExpectation == nil {
		mmCheckUsersExist.defaultExpectation = &UserRepositoryMockCheckUsersExistExpectation{}
	}

	if mmCheckUsersExist.defaultExpectation.paramPtrs != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by ExpectParams functions")
	}

	mmCheckUsersExist.defaultExpectation.params = &UserRepositoryMockCheckUsersExistParams{ctx, ids}
	for _, e := range mmCheckUsersExist.expectations {
		if minimock.Equal(e.params, mmCheckUsersExist.defaultExpectation.params) {
			mmCheckUsersExist.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCheckUsersExist.defaultExpectation.params)
		}
	}

	return mmCheckUsersExist
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.CheckUsersExist
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockCheckUsersExist {
	if mmCheckUsersExist.mock.funcCheckUsersExist != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Set")
	}

	if mmCheckUsersExist.defaultExpectation == nil {
		mmCheckUsersExist.defaultExpectation = &UserRepositoryMockCheckUsersExistExpectation{}
	}

	if mmCheckUsersExist.defaultExpectation.params != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Expect")
	}

	if mmCheckUsersExist.defaultExpectation.paramPtrs == nil {
		mmCheckUsersExist.defaultExpectation.paramPtrs = &UserRepositoryMockCheckUsersExistParamPtrs{}
	}
	mmCheckUsersExist.defaultExpectation.paramPtrs.ctx = &ctx

	return mmCheckUsersExist
}

// ExpectIdsParam2 sets up expected param ids for UserRepository.CheckUsersExist
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) ExpectIdsParam2(ids []int64) *mUserRepositoryMockCheckUsersExist {
	if mmCheckUsersExist.mock.funcCheckUsersExist != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Set")
	}

	if mmCheckUsersExist.defaultExpectation == nil {
		mmCheckUsersExist.defaultExpectation = &UserRepositoryMockCheckUsersExistExpectation{}
	}

	if mmCheckUsersExist.defaultExpectation.params != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Expect")
	}

	if mmCheckUsersExist.defaultExpectation.paramPtrs == nil {
		mmCheckUsersExist.defaultExpectation.paramPtrs = &UserRepositoryMockCheckUsersExistParamPtrs{}
	}
	mmCheckUsersExist.defaultExpectation.paramPtrs.ids = &ids

	return mmCheckUsersExist
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.CheckUsersExist
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Inspect(f func(ctx context.Context, ids []int64)) *mUserRepositoryMockCheckUsersExist {
	if mmCheckUsersExist.mock.inspectFuncCheckUsersExist != nil {
		mmCheckUsersExist.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.CheckUsersExist")
	}

	mmCheckUsersExist.mock.inspectFuncCheckUsersExist = f

	return mmCheckUsersExist
}

// Return sets up results that will be returned by UserRepository.CheckUsersExist
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Return(err error) *UserRepositoryMock {
	if mmCheckUsersExist.mock.funcCheckUsersExist != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Set")
	}

	if mmCheckUsersExist.defaultExpectation == nil {
		mmCheckUsersExist.defaultExpectation = &UserRepositoryMockCheckUsersExistExpectation{mock: mmCheckUsersExist.mock}
	}
	mmCheckUsersExist.defaultExpectation.results = &UserRepositoryMockCheckUsersExistResults{err}
	return mmCheckUsersExist.mock
}

// Set uses given function f to mock the UserRepository.CheckUsersExist method
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Set(f func(ctx context.Context, ids []int64) (err error)) *UserRepositoryMock {
	if mmCheckUsersExist.defaultExpectation != nil {
		mmCheckUsersExist.mock.t.Fatalf("Default expectation is already set for the UserRepository.CheckUsersExist method")
	}

	if len(mmCheckUsersExist.expectations) > 0 {
		mmCheckUsersExist.mock.t.Fatalf("Some expectations are already set for the UserRepository.CheckUsersExist method")
	}

	mmCheckUsersExist.mock.funcCheckUsersExist = f
	return mmCheckUsersExist.mock
}

// When sets expectation for the UserRepository.CheckUsersExist which will trigger the result defined by the following
// Then helper
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) When(ctx context.Context, ids []int64) *UserRepositoryMockCheckUsersExistExpectation {
	if mmCheckUsersExist.mock.funcCheckUsersExist != nil {
		mmCheckUsersExist.mock.t.Fatalf("UserRepositoryMock.CheckUsersExist mock is already set by Set")
	}

	expectation := &UserRepositoryMockCheckUsersExistExpectation{
		mock:   mmCheckUsersExist.mock,
		params: &UserRepositoryMockCheckUsersExistParams{ctx, ids},
	}
	mmCheckUsersExist.expectations = append(mmCheckUsersExist.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.CheckUsersExist return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockCheckUsersExistExpectation) Then(err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockCheckUsersExistResults{err}
	return e.mock
}

// Times sets number of times UserRepository.CheckUsersExist should be invoked
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Times(n uint64) *mUserRepositoryMockCheckUsersExist {
	if n == 0 {
		mmCheckUsersExist.mock.t.Fatalf("Times of UserRepositoryMock.CheckUsersExist mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCheckUsersExist.expectedInvocations, n)
	return mmCheckUsersExist
}

func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) invocationsDone() bool {
	if len(mmCheckUsersExist.expectations) == 0 && mmCheckUsersExist.defaultExpectation == nil && mmCheckUsersExist.mock.funcCheckUsersExist == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCheckUsersExist.mock.afterCheckUsersExistCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCheckUsersExist.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CheckUsersExist implements repository.UserRepository
func (mmCheckUsersExist *UserRepositoryMock) CheckUsersExist(ctx context.Context, ids []int64) (err error) {
	mm_atomic.AddUint64(&mmCheckUsersExist.beforeCheckUsersExistCounter, 1)
	defer mm_atomic.AddUint64(&mmCheckUsersExist.afterCheckUsersExistCounter, 1)

	if mmCheckUsersExist.inspectFuncCheckUsersExist != nil {
		mmCheckUsersExist.inspectFuncCheckUsersExist(ctx, ids)
	}

	mm_params := UserRepositoryMockCheckUsersExistParams{ctx, ids}

	// Record call args
	mmCheckUsersExist.CheckUsersExistMock.mutex.Lock()
	mmCheckUsersExist.CheckUsersExistMock.callArgs = append(mmCheckUsersExist.CheckUsersExistMock.callArgs, &mm_params)
	mmCheckUsersExist.CheckUsersExistMock.mutex.Unlock()

	for _, e := range mmCheckUsersExist.CheckUsersExistMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCheckUsersExist.CheckUsersExistMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCheckUsersExist.CheckUsersExistMock.defaultExpectation.Counter, 1)
		mm_want := mmCheckUsersExist.CheckUsersExistMock.defaultExpectation.params
		mm_want_ptrs := mmCheckUsersExist.CheckUsersExistMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockCheckUsersExistParams{ctx, ids}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCheckUsersExist.t.Errorf("UserRepositoryMock.CheckUsersExist got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.ids != nil && !minimock.Equal(*mm_want_ptrs.ids, mm_got.ids) {
				mmCheckUsersExist.t.Errorf("UserRepositoryMock.CheckUsersExist got unexpected parameter ids, want: %#v, got: %#v%s\n", *mm_want_ptrs.ids, mm_got.ids, minimock.Diff(*mm_want_ptrs.ids, mm_got.ids))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCheckUsersExist.t.Errorf("UserRepositoryMock.CheckUsersExist got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCheckUsersExist.CheckUsersExistMock.defaultExpectation.results
		if mm_results == nil {
			mmCheckUsersExist.t.Fatal("No results are set for the UserRepositoryMock.CheckUsersExist")
		}
		return (*mm_results).err
	}
	if mmCheckUsersExist.funcCheckUsersExist != nil {
		return mmCheckUsersExist.funcCheckUsersExist(ctx, ids)
	}
	mmCheckUsersExist.t.Fatalf("Unexpected call to UserRepositoryMock.CheckUsersExist. %v %v", ctx, ids)
	return
}

// CheckUsersExistAfterCounter returns a count of finished UserRepositoryMock.CheckUsersExist invocations
func (mmCheckUsersExist *UserRepositoryMock) CheckUsersExistAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCheckUsersExist.afterCheckUsersExistCounter)
}

// CheckUsersExistBeforeCounter returns a count of UserRepositoryMock.CheckUsersExist invocations
func (mmCheckUsersExist *UserRepositoryMock) CheckUsersExistBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCheckUsersExist.beforeCheckUsersExistCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.CheckUsersExist.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCheckUsersExist *mUserRepositoryMockCheckUsersExist) Calls() []*UserRepositoryMockCheckUsersExistParams {
	mmCheckUsersExist.mutex.RLock()

	argCopy := make([]*UserRepositoryMockCheckUsersExistParams, len(mmCheckUsersExist.callArgs))
	copy(argCopy, mmCheckUsersExist.callArgs)

	mmCheckUsersExist.mutex.RUnlock()

	return argCopy
}

// MinimockCheckUsersExistDone returns true if the count of the CheckUsersExist invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockCheckUsersExistDone() bool {
	if m.CheckUsersExistMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CheckUsersExistMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CheckUsersExistMock.invocationsDone()
}

// MinimockCheckUsersExistInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockCheckUsersExistInspect() {
	for _, e := range m.CheckUsersExistMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.CheckUsersExist with params: %#v", *e.params)
		}
	}

	afterCheckUsersExistCounter := mm_atomic.LoadUint64(&m.afterCheckUsersExistCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CheckUsersExistMock.defaultExpectation != nil && afterCheckUsersExistCounter < 1 {
		if m.CheckUsersExistMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.CheckUsersExist")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.CheckUsersExist with params: %#v", *m.CheckUsersExistMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCheckUsersExist != nil && afterCheckUsersExistCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.CheckUsersExist")
	}

	if !m.CheckUsersExistMock.invocationsDone() && afterCheckUsersExistCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.CheckUsersExist but found %d calls",
			mm_atomic.LoadUint64(&m.CheckUsersExistMock.expectedInvocations), afterCheckUsersExistCounter)
	}
}

type mUserRepositoryMockCreate struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockCreateExpectation
	expectations       []*UserRepositoryMockCreateExpectation

	callArgs []*UserRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockCreateExpectation specifies expectation struct of the UserRepository.Create
type UserRepositoryMockCreateExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockCreateParams
	paramPtrs *UserRepositoryMockCreateParamPtrs
	results   *UserRepositoryMockCreateResults
	Counter   uint64
}

// UserRepositoryMockCreateParams contains parameters of the UserRepository.Create
type UserRepositoryMockCreateParams struct {
	ctx  context.Context
	user *model.User
}

// UserRepositoryMockCreateParamPtrs contains pointers to parameters of the UserRepository.Create
type UserRepositoryMockCreateParamPtrs struct {
	ctx  *context.Context
	user **model.User
}

// UserRepositoryMockCreateResults contains results of the UserRepository.Create
type UserRepositoryMockCreateResults struct {
	i1  int64
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mUserRepositoryMockCreate) Optional() *mUserRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for UserRepository.Create
func (mmCreate *mUserRepositoryMockCreate) Expect(ctx context.Context, user *model.User) *mUserRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &UserRepositoryMockCreateParams{ctx, user}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.Create
func (mmCreate *mUserRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx

	return mmCreate
}

// ExpectUserParam2 sets up expected param user for UserRepository.Create
func (mmCreate *mUserRepositoryMockCreate) ExpectUserParam2(user *model.User) *mUserRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.user = &user

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.Create
func (mmCreate *mUserRepositoryMockCreate) Inspect(f func(ctx context.Context, user *model.User)) *mUserRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by UserRepository.Create
func (mmCreate *mUserRepositoryMockCreate) Return(i1 int64, err error) *UserRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &UserRepositoryMockCreateResults{i1, err}
	return mmCreate.mock
}

// Set uses given function f to mock the UserRepository.Create method
func (mmCreate *mUserRepositoryMockCreate) Set(f func(ctx context.Context, user *model.User) (i1 int64, err error)) *UserRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the UserRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the UserRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the UserRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mUserRepositoryMockCreate) When(ctx context.Context, user *model.User) *UserRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserRepositoryMock.Create mock is already set by Set")
	}

	expectation := &UserRepositoryMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &UserRepositoryMockCreateParams{ctx, user},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.Create return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockCreateExpectation) Then(i1 int64, err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockCreateResults{i1, err}
	return e.mock
}

// Times sets number of times UserRepository.Create should be invoked
func (mmCreate *mUserRepositoryMockCreate) Times(n uint64) *mUserRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of UserRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	return mmCreate
}

func (mmCreate *mUserRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements repository.UserRepository
func (mmCreate *UserRepositoryMock) Create(ctx context.Context, user *model.User) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, user)
	}

	mm_params := UserRepositoryMockCreateParams{ctx, user}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockCreateParams{ctx, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("UserRepositoryMock.Create got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmCreate.t.Errorf("UserRepositoryMock.Create got unexpected parameter user, want: %#v, got: %#v%s\n", *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("UserRepositoryMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the UserRepositoryMock.Create")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, user)
	}
	mmCreate.t.Fatalf("Unexpected call to UserRepositoryMock.Create. %v %v", ctx, user)
	return
}

// CreateAfterCounter returns a count of finished UserRepositoryMock.Create invocations
func (mmCreate *UserRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of UserRepositoryMock.Create invocations
func (mmCreate *UserRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mUserRepositoryMockCreate) Calls() []*UserRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*UserRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.Create with params: %#v", *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.Create")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.Create")
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.Create but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), afterCreateCounter)
	}
}

type mUserRepositoryMockDelete struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockDeleteExpectation
	expectations       []*UserRepositoryMockDeleteExpectation

	callArgs []*UserRepositoryMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockDeleteExpectation specifies expectation struct of the UserRepository.Delete
type UserRepositoryMockDeleteExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockDeleteParams
	paramPtrs *UserRepositoryMockDeleteParamPtrs
	results   *UserRepositoryMockDeleteResults
	Counter   uint64
}

// UserRepositoryMockDeleteParams contains parameters of the UserRepository.Delete
type UserRepositoryMockDeleteParams struct {
	ctx context.Context
	id  int64
}

// UserRepositoryMockDeleteParamPtrs contains pointers to parameters of the UserRepository.Delete
type UserRepositoryMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// UserRepositoryMockDeleteResults contains results of the UserRepository.Delete
type UserRepositoryMockDeleteResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mUserRepositoryMockDelete) Optional() *mUserRepositoryMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for UserRepository.Delete
func (mmDelete *mUserRepositoryMockDelete) Expect(ctx context.Context, id int64) *mUserRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &UserRepositoryMockDeleteParams{ctx, id}
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.Delete
func (mmDelete *mUserRepositoryMockDelete) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &UserRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for UserRepository.Delete
func (mmDelete *mUserRepositoryMockDelete) ExpectIdParam2(id int64) *mUserRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &UserRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.Delete
func (mmDelete *mUserRepositoryMockDelete) Inspect(f func(ctx context.Context, id int64)) *mUserRepositoryMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by UserRepository.Delete
func (mmDelete *mUserRepositoryMockDelete) Return(err error) *UserRepositoryMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &UserRepositoryMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &UserRepositoryMockDeleteResults{err}
	return mmDelete.mock
}

// Set uses given function f to mock the UserRepository.Delete method
func (mmDelete *mUserRepositoryMockDelete) Set(f func(ctx context.Context, id int64) (err error)) *UserRepositoryMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the UserRepository.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the UserRepository.Delete method")
	}

	mmDelete.mock.funcDelete = f
	return mmDelete.mock
}

// When sets expectation for the UserRepository.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mUserRepositoryMockDelete) When(ctx context.Context, id int64) *UserRepositoryMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("UserRepositoryMock.Delete mock is already set by Set")
	}

	expectation := &UserRepositoryMockDeleteExpectation{
		mock:   mmDelete.mock,
		params: &UserRepositoryMockDeleteParams{ctx, id},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.Delete return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockDeleteExpectation) Then(err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockDeleteResults{err}
	return e.mock
}

// Times sets number of times UserRepository.Delete should be invoked
func (mmDelete *mUserRepositoryMockDelete) Times(n uint64) *mUserRepositoryMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of UserRepositoryMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	return mmDelete
}

func (mmDelete *mUserRepositoryMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements repository.UserRepository
func (mmDelete *UserRepositoryMock) Delete(ctx context.Context, id int64) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := UserRepositoryMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("UserRepositoryMock.Delete got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("UserRepositoryMock.Delete got unexpected parameter id, want: %#v, got: %#v%s\n", *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("UserRepositoryMock.Delete got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the UserRepositoryMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to UserRepositoryMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished UserRepositoryMock.Delete invocations
func (mmDelete *UserRepositoryMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of UserRepositoryMock.Delete invocations
func (mmDelete *UserRepositoryMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mUserRepositoryMockDelete) Calls() []*UserRepositoryMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*UserRepositoryMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.Delete with params: %#v", *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.Delete")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.Delete with params: %#v", *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.Delete")
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.Delete but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), afterDeleteCounter)
	}
}

type mUserRepositoryMockGet struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockGetExpectation
	expectations       []*UserRepositoryMockGetExpectation

	callArgs []*UserRepositoryMockGetParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockGetExpectation specifies expectation struct of the UserRepository.Get
type UserRepositoryMockGetExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockGetParams
	paramPtrs *UserRepositoryMockGetParamPtrs
	results   *UserRepositoryMockGetResults
	Counter   uint64
}

// UserRepositoryMockGetParams contains parameters of the UserRepository.Get
type UserRepositoryMockGetParams struct {
	ctx    context.Context
	filter filter.UserFilter
}

// UserRepositoryMockGetParamPtrs contains pointers to parameters of the UserRepository.Get
type UserRepositoryMockGetParamPtrs struct {
	ctx    *context.Context
	filter *filter.UserFilter
}

// UserRepositoryMockGetResults contains results of the UserRepository.Get
type UserRepositoryMockGetResults struct {
	up1 *model.User
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mUserRepositoryMockGet) Optional() *mUserRepositoryMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for UserRepository.Get
func (mmGet *mUserRepositoryMockGet) Expect(ctx context.Context, filter filter.UserFilter) *mUserRepositoryMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UserRepositoryMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &UserRepositoryMockGetParams{ctx, filter}
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.Get
func (mmGet *mUserRepositoryMockGet) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UserRepositoryMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &UserRepositoryMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx

	return mmGet
}

// ExpectFilterParam2 sets up expected param filter for UserRepository.Get
func (mmGet *mUserRepositoryMockGet) ExpectFilterParam2(filter filter.UserFilter) *mUserRepositoryMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UserRepositoryMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &UserRepositoryMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.filter = &filter

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.Get
func (mmGet *mUserRepositoryMockGet) Inspect(f func(ctx context.Context, filter filter.UserFilter)) *mUserRepositoryMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by UserRepository.Get
func (mmGet *mUserRepositoryMockGet) Return(up1 *model.User, err error) *UserRepositoryMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &UserRepositoryMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &UserRepositoryMockGetResults{up1, err}
	return mmGet.mock
}

// Set uses given function f to mock the UserRepository.Get method
func (mmGet *mUserRepositoryMockGet) Set(f func(ctx context.Context, filter filter.UserFilter) (up1 *model.User, err error)) *UserRepositoryMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the UserRepository.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the UserRepository.Get method")
	}

	mmGet.mock.funcGet = f
	return mmGet.mock
}

// When sets expectation for the UserRepository.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mUserRepositoryMockGet) When(ctx context.Context, filter filter.UserFilter) *UserRepositoryMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("UserRepositoryMock.Get mock is already set by Set")
	}

	expectation := &UserRepositoryMockGetExpectation{
		mock:   mmGet.mock,
		params: &UserRepositoryMockGetParams{ctx, filter},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.Get return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockGetExpectation) Then(up1 *model.User, err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockGetResults{up1, err}
	return e.mock
}

// Times sets number of times UserRepository.Get should be invoked
func (mmGet *mUserRepositoryMockGet) Times(n uint64) *mUserRepositoryMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of UserRepositoryMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	return mmGet
}

func (mmGet *mUserRepositoryMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements repository.UserRepository
func (mmGet *UserRepositoryMock) Get(ctx context.Context, filter filter.UserFilter) (up1 *model.User, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, filter)
	}

	mm_params := UserRepositoryMockGetParams{ctx, filter}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockGetParams{ctx, filter}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("UserRepositoryMock.Get got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.filter != nil && !minimock.Equal(*mm_want_ptrs.filter, mm_got.filter) {
				mmGet.t.Errorf("UserRepositoryMock.Get got unexpected parameter filter, want: %#v, got: %#v%s\n", *mm_want_ptrs.filter, mm_got.filter, minimock.Diff(*mm_want_ptrs.filter, mm_got.filter))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("UserRepositoryMock.Get got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the UserRepositoryMock.Get")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, filter)
	}
	mmGet.t.Fatalf("Unexpected call to UserRepositoryMock.Get. %v %v", ctx, filter)
	return
}

// GetAfterCounter returns a count of finished UserRepositoryMock.Get invocations
func (mmGet *UserRepositoryMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of UserRepositoryMock.Get invocations
func (mmGet *UserRepositoryMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mUserRepositoryMockGet) Calls() []*UserRepositoryMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*UserRepositoryMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.Get with params: %#v", *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.Get")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.Get with params: %#v", *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.Get")
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.Get but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), afterGetCounter)
	}
}

type mUserRepositoryMockGetEndpointRoles struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockGetEndpointRolesExpectation
	expectations       []*UserRepositoryMockGetEndpointRolesExpectation

	callArgs []*UserRepositoryMockGetEndpointRolesParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockGetEndpointRolesExpectation specifies expectation struct of the UserRepository.GetEndpointRoles
type UserRepositoryMockGetEndpointRolesExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockGetEndpointRolesParams
	paramPtrs *UserRepositoryMockGetEndpointRolesParamPtrs
	results   *UserRepositoryMockGetEndpointRolesResults
	Counter   uint64
}

// UserRepositoryMockGetEndpointRolesParams contains parameters of the UserRepository.GetEndpointRoles
type UserRepositoryMockGetEndpointRolesParams struct {
	ctx      context.Context
	endpoint string
}

// UserRepositoryMockGetEndpointRolesParamPtrs contains pointers to parameters of the UserRepository.GetEndpointRoles
type UserRepositoryMockGetEndpointRolesParamPtrs struct {
	ctx      *context.Context
	endpoint *string
}

// UserRepositoryMockGetEndpointRolesResults contains results of the UserRepository.GetEndpointRoles
type UserRepositoryMockGetEndpointRolesResults struct {
	sa1 []string
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Optional() *mUserRepositoryMockGetEndpointRoles {
	mmGetEndpointRoles.optional = true
	return mmGetEndpointRoles
}

// Expect sets up expected params for UserRepository.GetEndpointRoles
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Expect(ctx context.Context, endpoint string) *mUserRepositoryMockGetEndpointRoles {
	if mmGetEndpointRoles.mock.funcGetEndpointRoles != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Set")
	}

	if mmGetEndpointRoles.defaultExpectation == nil {
		mmGetEndpointRoles.defaultExpectation = &UserRepositoryMockGetEndpointRolesExpectation{}
	}

	if mmGetEndpointRoles.defaultExpectation.paramPtrs != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by ExpectParams functions")
	}

	mmGetEndpointRoles.defaultExpectation.params = &UserRepositoryMockGetEndpointRolesParams{ctx, endpoint}
	for _, e := range mmGetEndpointRoles.expectations {
		if minimock.Equal(e.params, mmGetEndpointRoles.defaultExpectation.params) {
			mmGetEndpointRoles.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetEndpointRoles.defaultExpectation.params)
		}
	}

	return mmGetEndpointRoles
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.GetEndpointRoles
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockGetEndpointRoles {
	if mmGetEndpointRoles.mock.funcGetEndpointRoles != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Set")
	}

	if mmGetEndpointRoles.defaultExpectation == nil {
		mmGetEndpointRoles.defaultExpectation = &UserRepositoryMockGetEndpointRolesExpectation{}
	}

	if mmGetEndpointRoles.defaultExpectation.params != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Expect")
	}

	if mmGetEndpointRoles.defaultExpectation.paramPtrs == nil {
		mmGetEndpointRoles.defaultExpectation.paramPtrs = &UserRepositoryMockGetEndpointRolesParamPtrs{}
	}
	mmGetEndpointRoles.defaultExpectation.paramPtrs.ctx = &ctx

	return mmGetEndpointRoles
}

// ExpectEndpointParam2 sets up expected param endpoint for UserRepository.GetEndpointRoles
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) ExpectEndpointParam2(endpoint string) *mUserRepositoryMockGetEndpointRoles {
	if mmGetEndpointRoles.mock.funcGetEndpointRoles != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Set")
	}

	if mmGetEndpointRoles.defaultExpectation == nil {
		mmGetEndpointRoles.defaultExpectation = &UserRepositoryMockGetEndpointRolesExpectation{}
	}

	if mmGetEndpointRoles.defaultExpectation.params != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Expect")
	}

	if mmGetEndpointRoles.defaultExpectation.paramPtrs == nil {
		mmGetEndpointRoles.defaultExpectation.paramPtrs = &UserRepositoryMockGetEndpointRolesParamPtrs{}
	}
	mmGetEndpointRoles.defaultExpectation.paramPtrs.endpoint = &endpoint

	return mmGetEndpointRoles
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.GetEndpointRoles
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Inspect(f func(ctx context.Context, endpoint string)) *mUserRepositoryMockGetEndpointRoles {
	if mmGetEndpointRoles.mock.inspectFuncGetEndpointRoles != nil {
		mmGetEndpointRoles.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.GetEndpointRoles")
	}

	mmGetEndpointRoles.mock.inspectFuncGetEndpointRoles = f

	return mmGetEndpointRoles
}

// Return sets up results that will be returned by UserRepository.GetEndpointRoles
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Return(sa1 []string, err error) *UserRepositoryMock {
	if mmGetEndpointRoles.mock.funcGetEndpointRoles != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Set")
	}

	if mmGetEndpointRoles.defaultExpectation == nil {
		mmGetEndpointRoles.defaultExpectation = &UserRepositoryMockGetEndpointRolesExpectation{mock: mmGetEndpointRoles.mock}
	}
	mmGetEndpointRoles.defaultExpectation.results = &UserRepositoryMockGetEndpointRolesResults{sa1, err}
	return mmGetEndpointRoles.mock
}

// Set uses given function f to mock the UserRepository.GetEndpointRoles method
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Set(f func(ctx context.Context, endpoint string) (sa1 []string, err error)) *UserRepositoryMock {
	if mmGetEndpointRoles.defaultExpectation != nil {
		mmGetEndpointRoles.mock.t.Fatalf("Default expectation is already set for the UserRepository.GetEndpointRoles method")
	}

	if len(mmGetEndpointRoles.expectations) > 0 {
		mmGetEndpointRoles.mock.t.Fatalf("Some expectations are already set for the UserRepository.GetEndpointRoles method")
	}

	mmGetEndpointRoles.mock.funcGetEndpointRoles = f
	return mmGetEndpointRoles.mock
}

// When sets expectation for the UserRepository.GetEndpointRoles which will trigger the result defined by the following
// Then helper
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) When(ctx context.Context, endpoint string) *UserRepositoryMockGetEndpointRolesExpectation {
	if mmGetEndpointRoles.mock.funcGetEndpointRoles != nil {
		mmGetEndpointRoles.mock.t.Fatalf("UserRepositoryMock.GetEndpointRoles mock is already set by Set")
	}

	expectation := &UserRepositoryMockGetEndpointRolesExpectation{
		mock:   mmGetEndpointRoles.mock,
		params: &UserRepositoryMockGetEndpointRolesParams{ctx, endpoint},
	}
	mmGetEndpointRoles.expectations = append(mmGetEndpointRoles.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.GetEndpointRoles return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockGetEndpointRolesExpectation) Then(sa1 []string, err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockGetEndpointRolesResults{sa1, err}
	return e.mock
}

// Times sets number of times UserRepository.GetEndpointRoles should be invoked
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Times(n uint64) *mUserRepositoryMockGetEndpointRoles {
	if n == 0 {
		mmGetEndpointRoles.mock.t.Fatalf("Times of UserRepositoryMock.GetEndpointRoles mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetEndpointRoles.expectedInvocations, n)
	return mmGetEndpointRoles
}

func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) invocationsDone() bool {
	if len(mmGetEndpointRoles.expectations) == 0 && mmGetEndpointRoles.defaultExpectation == nil && mmGetEndpointRoles.mock.funcGetEndpointRoles == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetEndpointRoles.mock.afterGetEndpointRolesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetEndpointRoles.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetEndpointRoles implements repository.UserRepository
func (mmGetEndpointRoles *UserRepositoryMock) GetEndpointRoles(ctx context.Context, endpoint string) (sa1 []string, err error) {
	mm_atomic.AddUint64(&mmGetEndpointRoles.beforeGetEndpointRolesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetEndpointRoles.afterGetEndpointRolesCounter, 1)

	if mmGetEndpointRoles.inspectFuncGetEndpointRoles != nil {
		mmGetEndpointRoles.inspectFuncGetEndpointRoles(ctx, endpoint)
	}

	mm_params := UserRepositoryMockGetEndpointRolesParams{ctx, endpoint}

	// Record call args
	mmGetEndpointRoles.GetEndpointRolesMock.mutex.Lock()
	mmGetEndpointRoles.GetEndpointRolesMock.callArgs = append(mmGetEndpointRoles.GetEndpointRolesMock.callArgs, &mm_params)
	mmGetEndpointRoles.GetEndpointRolesMock.mutex.Unlock()

	for _, e := range mmGetEndpointRoles.GetEndpointRolesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmGetEndpointRoles.GetEndpointRolesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetEndpointRoles.GetEndpointRolesMock.defaultExpectation.Counter, 1)
		mm_want := mmGetEndpointRoles.GetEndpointRolesMock.defaultExpectation.params
		mm_want_ptrs := mmGetEndpointRoles.GetEndpointRolesMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockGetEndpointRolesParams{ctx, endpoint}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetEndpointRoles.t.Errorf("UserRepositoryMock.GetEndpointRoles got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.endpoint != nil && !minimock.Equal(*mm_want_ptrs.endpoint, mm_got.endpoint) {
				mmGetEndpointRoles.t.Errorf("UserRepositoryMock.GetEndpointRoles got unexpected parameter endpoint, want: %#v, got: %#v%s\n", *mm_want_ptrs.endpoint, mm_got.endpoint, minimock.Diff(*mm_want_ptrs.endpoint, mm_got.endpoint))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetEndpointRoles.t.Errorf("UserRepositoryMock.GetEndpointRoles got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetEndpointRoles.GetEndpointRolesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetEndpointRoles.t.Fatal("No results are set for the UserRepositoryMock.GetEndpointRoles")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmGetEndpointRoles.funcGetEndpointRoles != nil {
		return mmGetEndpointRoles.funcGetEndpointRoles(ctx, endpoint)
	}
	mmGetEndpointRoles.t.Fatalf("Unexpected call to UserRepositoryMock.GetEndpointRoles. %v %v", ctx, endpoint)
	return
}

// GetEndpointRolesAfterCounter returns a count of finished UserRepositoryMock.GetEndpointRoles invocations
func (mmGetEndpointRoles *UserRepositoryMock) GetEndpointRolesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetEndpointRoles.afterGetEndpointRolesCounter)
}

// GetEndpointRolesBeforeCounter returns a count of UserRepositoryMock.GetEndpointRoles invocations
func (mmGetEndpointRoles *UserRepositoryMock) GetEndpointRolesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetEndpointRoles.beforeGetEndpointRolesCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.GetEndpointRoles.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetEndpointRoles *mUserRepositoryMockGetEndpointRoles) Calls() []*UserRepositoryMockGetEndpointRolesParams {
	mmGetEndpointRoles.mutex.RLock()

	argCopy := make([]*UserRepositoryMockGetEndpointRolesParams, len(mmGetEndpointRoles.callArgs))
	copy(argCopy, mmGetEndpointRoles.callArgs)

	mmGetEndpointRoles.mutex.RUnlock()

	return argCopy
}

// MinimockGetEndpointRolesDone returns true if the count of the GetEndpointRoles invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockGetEndpointRolesDone() bool {
	if m.GetEndpointRolesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetEndpointRolesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetEndpointRolesMock.invocationsDone()
}

// MinimockGetEndpointRolesInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockGetEndpointRolesInspect() {
	for _, e := range m.GetEndpointRolesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.GetEndpointRoles with params: %#v", *e.params)
		}
	}

	afterGetEndpointRolesCounter := mm_atomic.LoadUint64(&m.afterGetEndpointRolesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetEndpointRolesMock.defaultExpectation != nil && afterGetEndpointRolesCounter < 1 {
		if m.GetEndpointRolesMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.GetEndpointRoles")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.GetEndpointRoles with params: %#v", *m.GetEndpointRolesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetEndpointRoles != nil && afterGetEndpointRolesCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.GetEndpointRoles")
	}

	if !m.GetEndpointRolesMock.invocationsDone() && afterGetEndpointRolesCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.GetEndpointRoles but found %d calls",
			mm_atomic.LoadUint64(&m.GetEndpointRolesMock.expectedInvocations), afterGetEndpointRolesCounter)
	}
}

type mUserRepositoryMockList struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockListExpectation
	expectations       []*UserRepositoryMockListExpectation

	callArgs []*UserRepositoryMockListParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockListExpectation specifies expectation struct of the UserRepository.List
type UserRepositoryMockListExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockListParams
	paramPtrs *UserRepositoryMockListParamPtrs
	results   *UserRepositoryMockListResults
	Counter   uint64
}

// UserRepositoryMockListParams contains parameters of the UserRepository.List
type UserRepositoryMockListParams struct {
	ctx    context.Context
	limit  int64
	offset int64
}

// UserRepositoryMockListParamPtrs contains pointers to parameters of the UserRepository.List
type UserRepositoryMockListParamPtrs struct {
	ctx    *context.Context
	limit  *int64
	offset *int64
}

// UserRepositoryMockListResults contains results of the UserRepository.List
type UserRepositoryMockListResults struct {
	upa1 []*model.User
	err  error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmList *mUserRepositoryMockList) Optional() *mUserRepositoryMockList {
	mmList.optional = true
	return mmList
}

// Expect sets up expected params for UserRepository.List
func (mmList *mUserRepositoryMockList) Expect(ctx context.Context, limit int64, offset int64) *mUserRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &UserRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.paramPtrs != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by ExpectParams functions")
	}

	mmList.defaultExpectation.params = &UserRepositoryMockListParams{ctx, limit, offset}
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.List
func (mmList *mUserRepositoryMockList) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &UserRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &UserRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ctx = &ctx

	return mmList
}

// ExpectLimitParam2 sets up expected param limit for UserRepository.List
func (mmList *mUserRepositoryMockList) ExpectLimitParam2(limit int64) *mUserRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &UserRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &UserRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.limit = &limit

	return mmList
}

// ExpectOffsetParam3 sets up expected param offset for UserRepository.List
func (mmList *mUserRepositoryMockList) ExpectOffsetParam3(offset int64) *mUserRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &UserRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &UserRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.offset = &offset

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.List
func (mmList *mUserRepositoryMockList) Inspect(f func(ctx context.Context, limit int64, offset int64)) *mUserRepositoryMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by UserRepository.List
func (mmList *mUserRepositoryMockList) Return(upa1 []*model.User, err error) *UserRepositoryMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &UserRepositoryMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &UserRepositoryMockListResults{upa1, err}
	return mmList.mock
}

// Set uses given function f to mock the UserRepository.List method
func (mmList *mUserRepositoryMockList) Set(f func(ctx context.Context, limit int64, offset int64) (upa1 []*model.User, err error)) *UserRepositoryMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the UserRepository.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the UserRepository.List method")
	}

	mmList.mock.funcList = f
	return mmList.mock
}

// When sets expectation for the UserRepository.List which will trigger the result defined by the following
// Then helper
func (mmList *mUserRepositoryMockList) When(ctx context.Context, limit int64, offset int64) *UserRepositoryMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("UserRepositoryMock.List mock is already set by Set")
	}

	expectation := &UserRepositoryMockListExpectation{
		mock:   mmList.mock,
		params: &UserRepositoryMockListParams{ctx, limit, offset},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.List return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockListExpectation) Then(upa1 []*model.User, err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockListResults{upa1, err}
	return e.mock
}

// Times sets number of times UserRepository.List should be invoked
func (mmList *mUserRepositoryMockList) Times(n uint64) *mUserRepositoryMockList {
	if n == 0 {
		mmList.mock.t.Fatalf("Times of UserRepositoryMock.List mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmList.expectedInvocations, n)
	return mmList
}

func (mmList *mUserRepositoryMockList) invocationsDone() bool {
	if len(mmList.expectations) == 0 && mmList.defaultExpectation == nil && mmList.mock.funcList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmList.mock.afterListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// List implements repository.UserRepository
func (mmList *UserRepositoryMock) List(ctx context.Context, limit int64, offset int64) (upa1 []*model.User, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx, limit, offset)
	}

	mm_params := UserRepositoryMockListParams{ctx, limit, offset}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.upa1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_want_ptrs := mmList.ListMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockListParams{ctx, limit, offset}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmList.t.Errorf("UserRepositoryMock.List got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.limit != nil && !minimock.Equal(*mm_want_ptrs.limit, mm_got.limit) {
				mmList.t.Errorf("UserRepositoryMock.List got unexpected parameter limit, want: %#v, got: %#v%s\n", *mm_want_ptrs.limit, mm_got.limit, minimock.Diff(*mm_want_ptrs.limit, mm_got.limit))
			}

			if mm_want_ptrs.offset != nil && !minimock.Equal(*mm_want_ptrs.offset, mm_got.offset) {
				mmList.t.Errorf("UserRepositoryMock.List got unexpected parameter offset, want: %#v, got: %#v%s\n", *mm_want_ptrs.offset, mm_got.offset, minimock.Diff(*mm_want_ptrs.offset, mm_got.offset))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("UserRepositoryMock.List got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results == nil {
			mmList.t.Fatal("No results are set for the UserRepositoryMock.List")
		}
		return (*mm_results).upa1, (*mm_results).err
	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx, limit, offset)
	}
	mmList.t.Fatalf("Unexpected call to UserRepositoryMock.List. %v %v %v", ctx, limit, offset)
	return
}

// ListAfterCounter returns a count of finished UserRepositoryMock.List invocations
func (mmList *UserRepositoryMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of UserRepositoryMock.List invocations
func (mmList *UserRepositoryMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mUserRepositoryMockList) Calls() []*UserRepositoryMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*UserRepositoryMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockListDone() bool {
	if m.ListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListMock.invocationsDone()
}

// MinimockListInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.List with params: %#v", *e.params)
		}
	}

	afterListCounter := mm_atomic.LoadUint64(&m.afterListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && afterListCounter < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.List")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.List with params: %#v", *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && afterListCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.List")
	}

	if !m.ListMock.invocationsDone() && afterListCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.List but found %d calls",
			mm_atomic.LoadUint64(&m.ListMock.expectedInvocations), afterListCounter)
	}
}

type mUserRepositoryMockUpdate struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockUpdateExpectation
	expectations       []*UserRepositoryMockUpdateExpectation

	callArgs []*UserRepositoryMockUpdateParams
	mutex    sync.RWMutex

	expectedInvocations uint64
}

// UserRepositoryMockUpdateExpectation specifies expectation struct of the UserRepository.Update
type UserRepositoryMockUpdateExpectation struct {
	mock      *UserRepositoryMock
	params    *UserRepositoryMockUpdateParams
	paramPtrs *UserRepositoryMockUpdateParamPtrs
	results   *UserRepositoryMockUpdateResults
	Counter   uint64
}

// UserRepositoryMockUpdateParams contains parameters of the UserRepository.Update
type UserRepositoryMockUpdateParams struct {
	ctx     context.Context
	updates *model.User
}

// UserRepositoryMockUpdateParamPtrs contains pointers to parameters of the UserRepository.Update
type UserRepositoryMockUpdateParamPtrs struct {
	ctx     *context.Context
	updates **model.User
}

// UserRepositoryMockUpdateResults contains results of the UserRepository.Update
type UserRepositoryMockUpdateResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdate *mUserRepositoryMockUpdate) Optional() *mUserRepositoryMockUpdate {
	mmUpdate.optional = true
	return mmUpdate
}

// Expect sets up expected params for UserRepository.Update
func (mmUpdate *mUserRepositoryMockUpdate) Expect(ctx context.Context, updates *model.User) *mUserRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.paramPtrs != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by ExpectParams functions")
	}

	mmUpdate.defaultExpectation.params = &UserRepositoryMockUpdateParams{ctx, updates}
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.Update
func (mmUpdate *mUserRepositoryMockUpdate) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &UserRepositoryMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.ctx = &ctx

	return mmUpdate
}

// ExpectUpdatesParam2 sets up expected param updates for UserRepository.Update
func (mmUpdate *mUserRepositoryMockUpdate) ExpectUpdatesParam2(updates *model.User) *mUserRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &UserRepositoryMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.updates = &updates

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.Update
func (mmUpdate *mUserRepositoryMockUpdate) Inspect(f func(ctx context.Context, updates *model.User)) *mUserRepositoryMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by UserRepository.Update
func (mmUpdate *mUserRepositoryMockUpdate) Return(err error) *UserRepositoryMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &UserRepositoryMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &UserRepositoryMockUpdateResults{err}
	return mmUpdate.mock
}

// Set uses given function f to mock the UserRepository.Update method
func (mmUpdate *mUserRepositoryMockUpdate) Set(f func(ctx context.Context, updates *model.User) (err error)) *UserRepositoryMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the UserRepository.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the UserRepository.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	return mmUpdate.mock
}

// When sets expectation for the UserRepository.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mUserRepositoryMockUpdate) When(ctx context.Context, updates *model.User) *UserRepositoryMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("UserRepositoryMock.Update mock is already set by Set")
	}

	expectation := &UserRepositoryMockUpdateExpectation{
		mock:   mmUpdate.mock,
		params: &UserRepositoryMockUpdateParams{ctx, updates},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.Update return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockUpdateExpectation) Then(err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockUpdateResults{err}
	return e.mock
}

// Times sets number of times UserRepository.Update should be invoked
func (mmUpdate *mUserRepositoryMockUpdate) Times(n uint64) *mUserRepositoryMockUpdate {
	if n == 0 {
		mmUpdate.mock.t.Fatalf("Times of UserRepositoryMock.Update mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdate.expectedInvocations, n)
	return mmUpdate
}

func (mmUpdate *mUserRepositoryMockUpdate) invocationsDone() bool {
	if len(mmUpdate.expectations) == 0 && mmUpdate.defaultExpectation == nil && mmUpdate.mock.funcUpdate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdate.mock.afterUpdateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Update implements repository.UserRepository
func (mmUpdate *UserRepositoryMock) Update(ctx context.Context, updates *model.User) (err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(ctx, updates)
	}

	mm_params := UserRepositoryMockUpdateParams{ctx, updates}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, &mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdate.UpdateMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockUpdateParams{ctx, updates}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdate.t.Errorf("UserRepositoryMock.Update got unexpected parameter ctx, want: %#v, got: %#v%s\n", *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.updates != nil && !minimock.Equal(*mm_want_ptrs.updates, mm_got.updates) {
				mmUpdate.t.Errorf("UserRepositoryMock.Update got unexpected parameter updates, want: %#v, got: %#v%s\n", *mm_want_ptrs.updates, mm_got.updates, minimock.Diff(*mm_want_ptrs.updates, mm_got.updates))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("UserRepositoryMock.Update got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the UserRepositoryMock.Update")
		}
		return (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(ctx, updates)
	}
	mmUpdate.t.Fatalf("Unexpected call to UserRepositoryMock.Update. %v %v", ctx, updates)
	return
}

// UpdateAfterCounter returns a count of finished UserRepositoryMock.Update invocations
func (mmUpdate *UserRepositoryMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of UserRepositoryMock.Update invocations
func (mmUpdate *UserRepositoryMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mUserRepositoryMockUpdate) Calls() []*UserRepositoryMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*UserRepositoryMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockUpdateDone() bool {
	if m.UpdateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateMock.invocationsDone()
}

// MinimockUpdateInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.Update with params: %#v", *e.params)
		}
	}

	afterUpdateCounter := mm_atomic.LoadUint64(&m.afterUpdateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && afterUpdateCounter < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UserRepositoryMock.Update")
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.Update with params: %#v", *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && afterUpdateCounter < 1 {
		m.t.Error("Expected call to UserRepositoryMock.Update")
	}

	if !m.UpdateMock.invocationsDone() && afterUpdateCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.Update but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateMock.expectedInvocations), afterUpdateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCheckUsersExistInspect()

			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetInspect()

			m.MinimockGetEndpointRolesInspect()

			m.MinimockListInspect()

			m.MinimockUpdateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCheckUsersExistDone() &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetDone() &&
		m.MinimockGetEndpointRolesDone() &&
		m.MinimockListDone() &&
		m.MinimockUpdateDone()
}
